### ISSUE TITLE
I am strangely upside-down!

### ISSUE THREAD

**Issue by siliconmeadow** [cgutteridge/geocraft#10]
<img width="1439" alt="minecraft_1_9" src="https://cloud.githubusercontent.com/assets/158008/14770445/cb3fe8c4-0a69-11e6-84e0-8b93df8e304f.png">

Minecraft 1.9 on Mac with Optifine HD B1 Ultra.

**Comment by cgutteridge** [comment]
Heh!
No, what's happened is that my generator doesn't set a world spawn point. That combines with the fact to speed it up it doesn't make anything under the map so you've spawned UNDER the world!

**Comment by siliconmeadow** [comment]
I see! I just punched a hole through and see what you mean.

Thanks!

Is that the way it behaves all the time?

**Comment by cgutteridge** [comment]
Yes, unless I change the code or you move to somewhere lower! You can use an in-game command to set the default spawn point.
