### ISSUE TITLE
Need to include an empty 'saves' directory?

### ISSUE THREAD

**Issue by illtud** [cgutteridge/geocraft#2]
Failed running first time as it doesn't create the saves dir. Simplest fix would be to include an empty one in the repo?

**Comment by cgutteridge** [comment]
D'oh. I fixed it, commited it and forgot to push. Now fixed.
https://github.com/cgutteridge/geocraft/commit/8da96c1241086ee7927ecfe396b2e79b47b67418
(how's that for service!?)

It creates the save directory if it doesn't exist, letting you make a symlink instead for convenience. A better feature would be to detect OS and default to the normal MC saves on that OS. I should also implement a way to select the saves dir on the command line...
