### ISSUE TITLE
Open Street Map Fails at getting Tiles

### ISSUE THREAD

**Issue by TechZack** [cgutteridge/geocraft#27]
The script seems like when it runs it gets some tiles but then after a few moments it then goes into a infinite loop and does not fetch any more tiles. Is there a way of not using tiles (OSM Tiles) and just having the blocks render.

Hopefully someone could try and find a way around this OpenStreetMaps area as the system doesn't past this point.

**Comment by amoraschi** [comment]
Is the map that you are rendering big? Because if it's more than 500 blocks, for me it takes about 20-30 minutes, it's slow but it gets the job done, I think it's not an infinite loop, it's actually generating

**Comment by RobinWhitfield** [comment]
@TechZackOfficial, I found that for me it would run for a couple of hours before failing to get OSM tiles (it'd tell me it couldn't find them, and indeed they did not exist in the folder it was searching in).

The continue flag proved invaluable to me for rendering a large map as then you can just quit the script when it fails and run it again from where it left off.
In the end I think it took me the best part of a week to get my 10k x 10k map.

**Comment by TechZack** [comment]
> Is the map that you are rendering big? Because if it's more than 500 blocks, for me it takes about 20-30 minutes, it's slow but it gets the job done, I think it's not an infinite loop, it's actually generating

I'm looking to get a very small radius of map so I'd say around 500 Blocks.

**Comment by cgutteridge** [comment]
what settings are you using? It should show a progress meter of a dot 
every 512 blocks!


On 23/11/2020 11:54, TechZack wrote:
> *CAUTION:* This e-mail originated outside the University of Southampton.
>
>     Is the map that you are rendering big? Because if it's more than
>     500 blocks, for me it takes about 20-30 minutes, it's slow but it
>     gets the job done, I think it's not an infinite loop, it's
>     actually generating
>
> I'm looking to get a very small radius of map so I'd say around 500 
> Blocks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F27%23issuecomment-732115243&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iehUcTLFjLEzGzH1a3ZeIBKlh85ciyeo0OkZFqclHiY%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V26JJHHQP3TXEAJAMILSRJEO7ANCNFSM4T63A5BQ&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WgORNTKAm%2FDkvlU4mtpH6%2BOHUFQMQEhw1peleU8wLAw%3D&reserved=0>.
>
-- 
Christopher Gutteridge <totl@soton.ac.uk>
You should read our team blog at http://blog.soton.ac.uk/webteam/

**Comment by TechZack** [comment]
> what settings are you using? It should show a progress meter of a dot every 512 blocks!
> On 23/11/2020 11:54, TechZack wrote: *CAUTION:* This e-mail originated outside the University of Southampton. Is the map that you are rendering big? Because if it's more than 500 blocks, for me it takes about 20-30 minutes, it's slow but it gets the job done, I think it's not an infinite loop, it's actually generating I'm looking to get a very small radius of map so I'd say around 500 Blocks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F27%23issuecomment-732115243&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iehUcTLFjLEzGzH1a3ZeIBKlh85ciyeo0OkZFqclHiY%3D&reserved=0>, or unsubscribe <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V26JJHHQP3TXEAJAMILSRJEO7ANCNFSM4T63A5BQ&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WgORNTKAm%2FDkvlU4mtpH6%2BOHUFQMQEhw1peleU8wLAw%3D&reserved=0>.
> -- Christopher Gutteridge <totl@soton.ac.uk> You should read our team blog at http://blog.soton.ac.uk/webteam/

![image](https://user-images.githubusercontent.com/44208067/99961409-4ae01880-2d86-11eb-9268-dff1f1e04015.png)
This is all im getting when generating OSM Tiles. This is just infinitely looping.

**Comment by cgutteridge** [comment]
I've just generated a test map using a fresh install and it worked but 
it looks like it's printing that message for every block!!

I suspect you might be happier if you edit lib/Elevation/UKDEFRA.pm  and 
"comment out" this line by putting a hash # at the start.

                 print "Using cached catalog: $catalog_cache_file\n";

It looks like it *is* working, but on my laptop it takes 10-20 minutes 
per *region* which is 512x512 blocks.


On 23/11/2020 12:21, TechZack wrote:
> *CAUTION:* This e-mail originated outside the University of Southampton.
>
>     what settings are you using? It should show a progress meter of a
>     dot every 512 blocks!
>     On 23/11/2020 11:54, TechZack wrote: /CAUTION:/ This e-mail
>     originated outside the University of Southampton. Is the map that
>     you are rendering big? Because if it's more than 500 blocks, for
>     me it takes about 20-30 minutes, it's slow but it gets the job
>     done, I think it's not an infinite loop, it's actually generating
>     I'm looking to get a very small radius of map so I'd say around
>     500 Blocks. — You are receiving this because you are subscribed to
>     this thread. Reply to this email directly, view it on GitHub
>     https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F27%23issuecomment-732115243&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iehUcTLFjLEzGzH1a3ZeIBKlh85ciyeo0OkZFqclHiY%3D&reserved=0
>     <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F27%23issuecomment-732115243&data=04%7C01%7Ctotl%40soton.ac.uk%7C6a4c33ce9c74437bcba408d88faa4976%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417308819052814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6GiER5i6CREfe4k3j2bYo4oJul%2FpE5jroEe2RGC1dGU%3D&reserved=0>,
>     or unsubscribe
>     https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V26JJHHQP3TXEAJAMILSRJEO7ANCNFSM4T63A5BQ&data=04%7C01%7Ctotl%40soton.ac.uk%7Cc26bdf877ac34e13d62108d88fa685fa%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417292654503111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WgORNTKAm%2FDkvlU4mtpH6%2BOHUFQMQEhw1peleU8wLAw%3D&reserved=0
>     <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V26JJHHQP3TXEAJAMILSRJEO7ANCNFSM4T63A5BQ&data=04%7C01%7Ctotl%40soton.ac.uk%7C6a4c33ce9c74437bcba408d88faa4976%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417308819052814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=63rLviTKt03uAWLsbtR8Vd1XZAU2BjoxLrOu4Con8aQ%3D&reserved=0>.
>     -- Christopher Gutteridge totl@soton.ac.uk
>     <mailto:totl@soton.ac.uk> You should read our team blog at
>     http://blog.soton.ac.uk/webteam/ <http://blog.soton.ac.uk/webteam/>
>
> image 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44208067%2F99961409-4ae01880-2d86-11eb-9268-dff1f1e04015.png&data=04%7C01%7Ctotl%40soton.ac.uk%7C6a4c33ce9c74437bcba408d88faa4976%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417308819062770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cwPwceztheZBsjixgS%2FFBzYG74Froxm0liaXL5Olrc0%3D&reserved=0>
> This is all im getting when generating OSM Tiles. This is just 
> infinitely looping.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F27%23issuecomment-732128467&data=04%7C01%7Ctotl%40soton.ac.uk%7C6a4c33ce9c74437bcba408d88faa4976%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417308819062770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qCV5yMtlZFh3AlP9SMAsA1xxGsPrkvFzjdzDj4Ra3lk%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V2334PCNQFPC43YO3MDSRJHUBANCNFSM4T63A5BQ&data=04%7C01%7Ctotl%40soton.ac.uk%7C6a4c33ce9c74437bcba408d88faa4976%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637417308819072730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UBwYqEkJJ1s2tU0eIEUHq5EloO6vo%2BnJ%2BRiyzJtz6C8%3D&reserved=0>.
>
-- 
Christopher Gutteridge <totl@soton.ac.uk>
You should read our team blog at http://blog.soton.ac.uk/webteam/

**Comment by TechZack** [comment]
> print "Using cached catalog: $catalog_cache_file\n";

I've added this to a comment so I'll get back to you if it completes.

**Comment by TechZack** [comment]
Seems like after some time it did work. Sadly it seemed like some of the data I was trying to use was flat and haven't been updated in a while. Which I can't blame on this script.
