### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by pointlessspyguy** [cgutteridge/geocraft#28]
I run the generate-world command, and it tells me " -bash: ./generate-world: Permission denied"

**Comment by cgutteridge** [comment]
Permissions?

Try

chmod 755 generate-world

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pointlessspyguy** [comment]
Still says it...

**Comment by cgutteridge** [comment]
I've not forgotten this but don't have a quick answer. It feels like the 
file perm is wrong but could be something else.

Do you have perl installed?

On 29/01/2021 20:54, pointlessspyguy wrote:
> *CAUTION:* This e-mail originated outside the University of Southampton.
>
> Still says it...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F28%23issuecomment-770044450&data=04%7C01%7Ctotl%40soton.ac.uk%7C7d4bd5a729da48b9eb3508d8c4980f91%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637475504657427131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O7LsB5EQZZLwFr8W1x6itiCt9LCQwMdG%2Bhg6pAAFVus%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V23DRLRLHBGC4DSOAOLS4MN77ANCNFSM4WZKVOXQ&data=04%7C01%7Ctotl%40soton.ac.uk%7C7d4bd5a729da48b9eb3508d8c4980f91%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637475504657427131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dRfWbjDzYJcoOJoKTwRG6XWjL29vJopLmY5YPQPCSXI%3D&reserved=0>.
>
-- 
Christopher Gutteridge <totl@soton.ac.uk>
You should read our team blog at http://blog.soton.ac.uk/webteam/

**Comment by pointlessspyguy** [comment]
K, I figured it out, it's because I was using a Linux emulator for android, and I couldn't get the world to load, because I tried to execute the program through the sdcard, not the virtual storage with the emulator, so we're good here

**Comment by cgutteridge** [comment]
Oh, wow, I'd not have guessed that one! Thanks very much for the info 
rather than just wondering off when you solved it yourself.

On 08/02/2021 15:46, pointlessspyguy wrote:
> *CAUTION:* This e-mail originated outside the University of Southampton.
>
> K, I figured it out, it's because I was using a Linux emulator for 
> android, and I couldn't get the world to load, because I tried to 
> execute the program through the sdcard, not the virtual storage with 
> the emulator, so we're good here
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcgutteridge%2Fgeocraft%2Fissues%2F28%23issuecomment-775241351&data=04%7C01%7Ctotl%40soton.ac.uk%7C8b9573e6ccde4253fad908d8cc48a86e%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637483959764485255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nzrQv7d%2FTkWb5AWZursvAZ4tQGUXv9rDpuv1LC1R8RI%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAD4V2ZQM7QBYXOBFBT5MYLS6ABMDANCNFSM4WZKVOXQ&data=04%7C01%7Ctotl%40soton.ac.uk%7C8b9573e6ccde4253fad908d8cc48a86e%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637483959764495208%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tuh2xzOYFhJmWBb6JZpI6A1TbQDn5oiMq6zWev%2FIZ8o%3D&reserved=0>.
>
-- 
Christopher Gutteridge <totl@soton.ac.uk>
You should read our team blog at http://blog.soton.ac.uk/webteam/
