### ISSUE TITLE
Beginner Error 

### ISSUE THREAD

**Issue by syqthe** [cgutteridge/geocraft#30]
./generate-world --postcode SO171BJ --size 1000 d --replace

World exists, removing it
Cloning 'bedrock' as a base world
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<html>\r\n<head><tit...") at ./generate-world line 368.

**Comment by einc123** [comment]
same, any ideas?

**Comment by BlitzdUK** [comment]
> same, any ideas?

i was able to fix this by changing all the http links with https in the generate-world file

**Comment by cgutteridge** [comment]
Thanks. Sorry for the lack of love on this project... I've pushed a fix.
