### ISSUE TITLE
Proposal: allow running without elevation

### ISSUE THREAD

**Issue by kekscom** [cgutteridge/geocraft#5]
For converting Berlin I had no suitable elevation data at hand.
I would be useful to be able to run without it.
Right now I did a hack by always returning elevation 0.

**Comment by jargonautical** [comment]
@kekscom could you share that hack with me? I think I'm hitting a similar problem and that might fix it for this one world I'm working on.

**Comment by kekscom** [comment]
@cgutteridge Made a change that allows parameter `--elevation Flat`
That should help.

**Comment by jargonautical** [comment]
@kekscom thanks - that worked :)
