### ISSUE TITLE
Proposal: allow other projections than OSGB36

### ISSUE THREAD

**Issue by kekscom** [cgutteridge/geocraft#6]
Providing a bounding box in EPSG4326 is a very common case.
I've seen preparations in the code. Would be nice to have something official.

**Comment by cgutteridge** [comment]
That's the OSM projection, right? How would that look on the command line? An alternate to the -ll option? 

I suspect it might also be useful to offer that as a projection as the one I've used for Easting/Northing is very UK centric. Problem is that projection stretches shapes the further you are from the equator.

**Comment by kekscom** [comment]
Lets say its the common web rastermap projection.
I've changed quite some places in code in order to make --from and --to working whith these.

I'll try to show you these as well. However, supporting geo transformation in a more flexible way would give geocraft a big boost.

Just found, there is a Proj4 Package for Perl: http://search.cpan.org/~sderle/Geo-Proj4-0.11/Proj4.pm Recommend!
