### ISSUE TITLE
Proposal: make use of OSM vector data rather than bitmap analysis

### ISSUE THREAD

**Issue by kekscom** [cgutteridge/geocraft#7]
Drawback of vector might be rasterization effort. OTOH yoi get much clearer information about feature types.
There are already nice data services like https://mapzen.com/projects/vector-tiles/

I could also provide you with pre-rasterad data via http://osmbuildings.org/

**Comment by cgutteridge** [comment]
The system I've used could easily be changed to use alternate tiles. The 
ideal tiles would have no line-borders on polygons, no text and no 
anti-aliasing.

To try it out with alternate map tiles, edit the tile URL in 
generate-world and colour. You can then pick lat/long locations from the 
tiles to see what the colour is, and update a copy of the colours config 
file for that tileset.

I use http://lemur.ecs.soton.ac.uk/~cjg/clickymap/ to get the lat/long 
for the thing I'm interested in and then ./colour --ll --point 
50.93659,-1.39536

On 04/02/2016 09:58, Jan Marsch wrote:

> Drawback of vector might be rasterization effort OTOH yoi get much 
> clearer information about feature types
> There are already nice data services like 
> https://mapzencom/projects/vector-tiles/
> 
> I could also provide you with pre-rasterad data via 
> http://osmbuildingsorg/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cgutteridge/geocraft/issues/7.Web Bug from 
> https://github.com/notifications/beacon/AAfK60KaEYg9yQ-gNr0r0_bApg_u1LmZks5pgxg6gaJpZM4HTOTF.gif

## 

Christopher Gutteridge -- http://users.ecs.soton.ac.uk/cjg

University of Southampton Open Data Service: http://data.southampton.ac.uk/
You should read the ECS Web Team blog: http://blogs.ecs.soton.ac.uk/webteam/

**Comment by kekscom** [comment]
I've seen it.
Alternate map tiles would also mean redefinition of colors. Not to mention anti alias etc.
However, I like the idea for simplicity.

Meanwhile I have proper X/Y/Z rasterization for buildings in place.
Just need to connect to geocraft via synchronous coordinates.
Plus removal of the current building detection.

I'll show you a demo asap.

For coordinate picking, I can recommend http://osm.org ("Export").
But still I didn't manage to configure with --ll
See #6
